# Database settings
spring:
  datasource:
    url: jdbc:derby:${user.home}/.mcdb/db;create=true
    initialization-mode: never
    platform: derby
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
---
# Hibernate Settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
      # database-platform: org.hibernate.dialect.DerbyDialect
    properties:
      hibernate:
        default_schema: APP
        enable_lazy_load_no_trans: true
        search:
          default:
            directory_provider: filesystem
            indexBase: ${user.home}/.mcdb/index
---
logging:
  level:
    org.springframework.web: ERROR
    org.kathrynhuxtable: INFO
    org.apache: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ${user.home}/.mcdb/mcdb.log
---
mcdb:
  data-directory: ${user.home}/.mcdb
  help-destination: ${user.home}/.mcdb/help
  help-url: file://${user.home}/.mcdb/help/mcdb.html
